# These are supported funding model platforms

custom: {
  "Instagram": {
    "name": "@bagussatoto1",
    "url": "https://www.instagram.com/p/{code}",
    "color": "#e1306c",
    "logo": "instagram.png"
  },
  "Facebook": {
    "name": "bagussatoto1",
    "url": "https://www.facebook.com/bagussatoto1",
    "color": "#3b5998",
    "logo": "facebook.png"
  },
  "github": {
    "name": "bagussatoto1",
    "url": "https://github.com/bagussatoto",
    "color": "#24292e",
    "logo": "github.png"
  },